repos:  
  - repo: local  
    hooks:  
      - id: detekt  
        name: detekt check  
        description: Runs `detekt` on modified .kt files.  
        language: script  
        entry: ./PedometerApp/scripts/detekt.sh  
        files: \.kt
